# Generated by Django 2.2 on 2022-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0004_order_fix_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
